# Generated by Django 3.2.14 on 2022-12-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_paciente_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='fecha',
            field=models.DateTimeField(default=None, verbose_name='Fecha'),
        ),
    ]
